<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="stand_mass"   value="2" /> 
    <xacro:property name="stand_radius" value="0.03"/>
    <xacro:property name="stand_length" value="0.4"/>

    <xacro:include filename="$(find marm_description)/urdf/mbot_base_gazebo.xacro" />
    <xacro:include filename="$(find marm_description)/urdf/arm_base_gazebo.xacro" />

    <mbot_base_gazebo/>

    <joint name="base_stand_joint" type="fixed">
        <origin xyz="0 0 ${stand_length/2+0.08}" rpy="0 0 0" />        
        <parent link="base_link"/>
        <child link="stand" />
    </joint>

    <link name="stand">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${stand_length}" radius="${stand_radius}"/>
            </geometry>
            <material name="gray" />
        </visual>
        <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${stand_length}" radius="${stand_radius}"/>
            </geometry>
        </collision>   
        <cylinder_inertial_matrix  m="${stand_mass}" r="${stand_radius}" h="${stand_length}" />
    </link>

    <gazebo reference="stand">
        <material>Gazebo/Gray</material>
    </gazebo>

    <arm_base parent="stand" xyz="0 0 0" rpy="${M_PI/2} 0 0"/>

</robot>
